image: ubuntu/bionic

packages:
  - cmake
  - gdal-dev
  - libboost-date-time-dev
  - libboost-program-options-dev
  - libboost-test-dev
  - qt4-dev-tools

sources:
  - https://github.com/firelab/windninja

tasks:
  - build: |
      cd windninja
      mkdir build
      cd build
      cmake ..
      make

  - test: |
      export WINDNINJA_DATA=~/windninja/data
      cd windninja/build
      ctest
