env:
  global:

language: cpp

dist: bionic

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqtwebkit-dev cmake python libspatialite-dev libgeos-dev libgdal-dev libnetcdf-dev libboost-date-time-dev libboost-program-options-dev libboost-test-dev

install:
  - export WINDNINJA_DATA=$PWD/data
  - mkdir build
  - cd build
  - cmake -D SUPRESS_WARNINGS=ON  -D SKIP_GETDATE=ON -D BUILD_TESTING=ON -D DISABLE_THREDDS_UPDATE=ON -D OPENMP_SUPPORT=ON -D RUN_CFG_TESTS=ON -D STABILITY=ON -D WITH_LCP_CLIENT=ON -D CMAKE_BUILD_TYPE=debug -D NINJA_CLI=ON  ..
  - make -j3

script:
    - ctest -E 'landfire|rtma|cfg_ucar_nam|cfg_wx1_config|cfg_mesonet_point|cfg_nomads_arw_ak|cfg_nomads_arw_conus'

# branches to skip
branches:
  except:
  - "para-nomads"
  - "gh-pages"
  - "gh"
  - "qt5-ui"

notifications:
  email:
    recipients:
      - kyle@pobox.com
      - nwagenbrenner@gmail.com
      - jforthofer@gmail.com
      - levi@third.consulting

  irc:
    channels:
      - "irc.freenode.org#windninja"
    use_notice: true
