env:
  global:

language: cpp

compiler:
  - gcc

# remove libogdi3.2-dev : it pulls projects.h from PROJ.4 which no longer exists
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - sudo apt-get install python libgdal-dev libnetcdf-dev libboost-date-time-dev libboost-program-options-dev libboost-test-dev

install:
  - mkdir build
  - cd build
  - cmake -D BUILD_TESTING=ON -D DISABLE_THREDDS_UPDATE=ON -D OPENMP_SUPPORT=ON -D RUN_CLI_TESTS=ON -D STABILITY=ON -D WITH_LCP_CLIENT=ON -D CMAKE_BUILD_TYPE=debug -D NINJA_CLI=ON  ..
  - make -j3

script:
  - ctest -R config

notifications:
  email:
    recipients:
      - kyle@pobox.com

  irc:
    channels:
      - "irc.freenode.org#windninja"
    use_notice: true
