env:
  global:

language: cpp

compiler:
  - gcc

# remove libogdi3.2-dev : it pulls projects.h from PROJ.4 which no longer exists
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - sudo apt-get install libgdal-dev libnetcdf-dev libboost-date-time-dev libboost-program-options-dev libboost-test-dev

install:
  - mkdir build
  - cd build
  - cmake ..
  - make -j3

script:
  - ctest -R config

notifications:
  email:
    recipients:
      - kyle@pobox.com

  irc:
    channels:
      - "irc.freenode.org#windninja"
    use_notice: true
