env:
  global:

language: cpp

compiler:
  - gcc

before_install:
  - wget "https://cmake.org/files/v3.5/cmake-3.5.0.tar.gz"
  - tar -xvf cmake-3.5.0.tar.gz
  - cd cmake-3.5.0/
  - ./configure && make -j3 && sudo make install
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - sudo apt-get install python libgdal-dev libnetcdf-dev libboost-date-time-dev libboost-program-options-dev libboost-test-dev

install:
  - mkdir build
  - cd build
  - cmake -D BUILD_TESTING=ON -D DISABLE_THREDDS_UPDATE=ON -D OPENMP_SUPPORT=ON -D RUN_CFG_TESTS=ON -D STABILITY=ON -D WITH_LCP_CLIENT=ON -D CMAKE_BUILD_TYPE=debug -D NINJA_CLI=ON  ..
  - make -j3

script:
  - ctest -R config

notifications:
  email:
    recipients:
      - kyle@pobox.com

  irc:
    channels:
      - "irc.freenode.org#windninja"
    use_notice: true
