# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WindNinja
email: tfinney@fs.fed.us
description: > # this means to ignore newlines until "baseurl:"
  Jannik Richter, jannik811@gmail.com
  Tanner Finney, tfinney@fs.fed.us
baseurl: "/windninja" # the subpath of your site, e.g. /blog
url: "http://firelab.github.io/windninja/" # the base hostname & protocol for your site
twitter_username: null
github_username:  tfinney9

# Build settings
markdown: kramdown
