name: Testing

on:
  push:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release
  WINDNINJA_DATA: ${{github.workspace}}/data

jobs:
  build:
    runs-on: ubuntu-20.04
   
    steps:
    - uses: actions/checkout@v3
    
    - name: Cache Build Dependencies
      id: cacheDep
      uses: actions/cache@v2
      with:
        path: |
          ${{github.workspace}}/poppler-0.23.4
          ${{github.workspace}}/proj-6.3.2
          ${{github.workspace}}/gdal-3.2.1
        key: ${{ runner.os }}-windDep
        restore-keys: ${{ runner.os }}-windDep
        
    - name: check cacheing, dir contents
      run: |
        echo "running pwd"
        pwd
        echo "running ls -la"
        ls -la
    
    - name: build dependencies
      if: steps.cacheDep.outputs.cache-hit != 'true'
      run: ${{github.workspace}}/scripts/build_deps_ubuntu_2004.sh

    - name: make build directory
      run: mkdir build

    - name: configure
      working-directory: ${{github.workspace}}/build
      run: cmake -B ${{github.workspace}}/build -D SUPRESS_WARNINGS=ON  -D SKIP_GETDATE=ON -D BUILD_TESTING=ON -D DISABLE_THREDDS_UPDATE=ON -D OPENMP_SUPPORT=ON -D RUN_CFG_TESTS=ON -D STABILITY=ON -D WITH_LCP_CLIENT=ON -D CMAKE_BUILD_TYPE=debug -D NINJA_CLI=ON ..

    - name: make
      working-directory: ${{github.workspace}}/build
      run: make && sudo make install
      
    - name: test
      working-directory: ${{github.workspace}}/build
      #skip cfg tests until UCAR THREDDS service is fixed
      run: echo "${{env.WINDNINJA_DATA}}" && ctest --output-on-failure -E 'cfg_ucar_rap|cfg_ucar_ndfd|cfg_ucar_gfs|landfire|rtma|cfg_ucar_nam|cfg_wx1_config|cfg_mesonet_point|cfg_nomads_arw_ak|cfg_nomads_arw_conus'
